from zhuge.model.BaseModel.Base import Base


class ComplexGovDel(Base):
    __tablename__ = 'complex_gov_del'

    fields = {
        'id': 0,
        'complex_pinyin': '',
        'city_id': 0,
        'complex_id': 0,
        'utime': 0,
        'base_id': 0,
        'subway_info': '',
        'complex_name': '',
        'complex_alias': '',
        'complex_address': '',
        'source_id': 0,
        'source_url': '',
        'cityarea2_name': '',
        'cityarea_name': '',
        'cityarea2_id': '',
        'cityarea_id': 0,
        'complex_tag': '',
        'complex_building_type': '',
        'complex_loopline': 0,
        'developer_name': '',
        'hot_line': '',
        'developer_offer_expiry': '',
        'developer_offer': '',
        'sale_status': '',
        'preferential_status': '',
        'property_company': '',
        'property_type': '',
        'property_costs': '',
        'hydropower_gas': '',
        'heating_mode': '',
        'greening_rate': '',
        'parking_rate': '',
        'parking_count': '',
        'volume_rate': '',
        'renovation': '',
        'first_saletime': 0,
        'firstnew_saletime': 0,
        'first_delivertime': '',
        'license': '',
        'lng': 0.0,
        'lat': 0.0,
        'priority': '',
        'property_year': '',
        'take_land_time': '',
        'ctime': 0,
        'sortweight': 0,
        'first_logic_saletime': 0,
        'complex_desc': '',
        'cityarea_pinyin': '',
        'cityarea2_pinyin': '',
        'architectural': '',
        'salesoffice_address': '',
        'building_totalarea': '',
        'building_area': '',
        'building_total': '',
        'house_total': '',
        'property_desc': '',
        'floor_desc': '',
        'property_id': 0,
        'developer_id': 0,
        'location_type': 0,
        'checked': 0,
        'developer_price': 0,
        'developer_price_unit': '',
        'around_average_price': '',
        'offline_status': 0,
        'cms_id': 0,
    }
